---
- name: Ensure old versions of Docker are not installed.
  ansible.builtin.package:
    name:
      - docker
      - docker-common
      - docker-engine
    state: absent
  register: __pkg_result
  retries: 12
  delay: 10
  until: __pkg_result is success

- name: Add Docker GPG key.
  ansible.builtin.rpm_key:
    key: "{{ docker_yum_gpg_key }}"
    state: present
  when: docker_add_repo | bool

- name: Add Docker repository.
  ansible.builtin.get_url:
    url: "{{ docker_yum_repo_url }}"
    dest: '/etc/yum.repos.d/docker-{{ docker_edition }}.repo'
    owner: root
    group: root
    mode: '0644'
  when: docker_add_repo | bool

- name: Configure Docker Nightly repo
  ansible.builtin.lineinfile:
    path: "{{ docker_yum_repo_file | default('/etc/yum.repos.d/docker-ce.repo') }}"
    regexp: '^\s*enabled\s*='
    line: 'enabled={{ docker_yum_repo_enable_nightly }}'
    insertafter: '\[docker-ce-nightly\]'
    mode: '0644'
  when: docker_add_repo | bool

- name: Configure Docker Test repo
  ansible.builtin.lineinfile:
    path: "{{ docker_yum_repo_file | default('/etc/yum.repos.d/docker-ce.repo') }}"
    regexp: '^\s*enabled\s*='
    line: 'enabled={{ docker_yum_repo_enable_test }}'
    insertafter: '\[docker-ce-test\]'
    mode: '0644'
  when: docker_add_repo | bool

- name: Configure containerd on RHEL 8.
  when: ansible_distribution_major_version | int == 8
  block:
    - name: Ensure runc is not installed.
      ansible.builtin.package:
        name: runc
        state: absent
      register: __pkg_result
      retries: 12
      delay: 10
      until: __pkg_result is success

    - name: Ensure container-selinux is installed.
      ansible.builtin.package:
        name: container-selinux
        state: present
      register: __pkg_result
      retries: 12
      delay: 10
      until: __pkg_result is success

    - name: Ensure containerd.io is installed.
      ansible.builtin.package:
        name: containerd.io
        state: present
      register: __pkg_result
      retries: 12
      delay: 10
      until: __pkg_result is success
